protected/models/Clients.php
<?php

/**
 * This is the model class for table "{{clients}}".
 *
 * The followings are the available columns in table '{{clients}}':
 * @property integer $cid
 * @property string $name
 * @property string $nick_name
 * @property integer $project_type
 * @property string $description
 * @property integer $status
 * @property string $created_date
 * @property integer $created_by
 * @property string $updated_date
 * @property integer $updated_by
 *
 * The followings are the available model relations:
 * @property ProjectType $projectType
 * @property Status $status0
 * @property Users $createdBy
 * @property Users $updatedBy
 * @property Invoice[] $invoices
 * @property Projects[] $projects
 */

class Clients extends CActiveRecord
{	
	 public $status = 1;  //default radio button selection on create.
	 public $nick_name;
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Clients the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{clients}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name, project_type, status, created_date, created_by, updated_date, updated_by', 'required'),
			array('project_type, status, created_by, updated_by', 'numerical', 'integerOnly'=>true),
			array('name, nick_name', 'length', 'max'=>100),
			array('description', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('cid, name, nick_name, project_type, description, status, created_date, created_by, updated_date, updated_by', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'projectType' => array(self::BELONGS_TO, 'ProjectType', 'project_type'),
			'status0' => array(self::BELONGS_TO, 'Status', 'status'),
			'createdBy' => array(self::BELONGS_TO, 'Users', 'created_by'),
			'updatedBy' => array(self::BELONGS_TO, 'Users', 'updated_by'),
			'invoices' => array(self::HAS_MANY, 'Invoice', 'client_id'),
			'projects' => array(self::HAS_MANY, 'Projects', 'client_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'cid' => 'Cid',
			'name' => 'Name',
			'nick_name' => 'Nick Name',
			'project_type' => 'Project Type',
			'description' => 'Description',
			'status' => 'Status',
			'created_date' => 'Created Date',
			'created_by' => 'Created By',
			'updated_date' => 'Updated Date',
			'updated_by' => 'Updated By',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('cid',$this->cid);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('nick_name',$this->nick_name,true);
		$criteria->compare('project_type',$this->project_type);
		$criteria->compare('description',$this->description,true);
		$criteria->compare('status',$this->status);
		$criteria->compare('created_date',$this->created_date,true);
		$criteria->compare('created_by',$this->created_by);
		$criteria->compare('updated_date',$this->updated_date,true);
		$criteria->compare('updated_by',$this->updated_by);

		  return new CActiveDataProvider($this, array('pagination' => array('pageSize' => 25,),
                    'criteria' => $criteria,'sort' => array(
                        'defaultOrder' => 'cid desc',),
                ));
	}

	 public function getViewname(){
       if(yii::app()->user->mainuser_role==1){
           return 1;
       }else{
           return 0;
       }
        
    }

}

protected/controllers/ClientsController.php
<?php

class ClientsController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/column2';
    public $accessArr = array();
    public $accessauthArr = array();
    public $accessguestArr = array();
    
    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        
        
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view'),
                'users' => array('@'),		 		
            ),
            
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('create', 'update', 'admin','addclient','viewpartial'),
                'users' => array('@'),
		 		       'expression' => 'yii::app()->user->role<=2',
            ),
      			array('deny',  // deny all users
      				'users'=>array('*'),
      			),
         
        );
        
        
        
    /*    return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'view', 'viewpartial'),
                'users' => array('*'),
		 'expression' => 'yii::app()->user->role<=2',
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions' => array('create', 'update', 'admin'),
                'users' => array('@'),
                'expression' => 'yii::app()->user->role<=2',
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin', 'delete'),
                'users' => array('@'),
                'expression' => 'yii::app()->user->role==1',
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        ); */
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionViewpartial($id) {
        $this->renderPartial('view', array(
            'model' => $this->loadModel($id),
        ));
    }

    public function actionView1($id) {
        if (Yii::app()->request->isAjaxRequest) {
            //outputProcessing = true because including css-files ...
            $this->renderPartial('view', array(
                'model' => $this->loadModel($id),
                    ), false, true);
            //js-code to open the dialog    
            if (!empty($_GET['asDialog']))
                echo CHtml::script('$("#dlg-clients-view").dialog("open")');
            Yii::app()->end();
        } else
            $listproject = Projects::model()->findAllByAttributes(array(
                'client_id' => $id,
            ));

        $this->render('view', array(
            'model' => $this->loadModel($id), 'getdata' => $listproject, 
        ));
    }
  public function actionView($id) {
//        	if ( isset( $_GET[ 'pageSizes' ] ) )
//{
//Yii::app()->user->setState( 'pageSizes', (int) $_GET[ 'pageSizes' ] );
//unset( $_GET[ 'pageSizes' ] );
//} 

  
        if (Yii::app()->request->isAjaxRequest) {
            //outputProcessing = true because including css-files ...
            $this->renderPartial('view', array(
                'model' => $this->loadModel($id),
                    ), false, true);
            //js-code to open the dialog    
            if (!empty($_GET['asDialog']))
                echo CHtml::script('$("#dlg-clients-view").dialog("open")');
            Yii::app()->end();
        } else
        $Criteria = new CDbCriteria();
        $Criteria->select = "*";

        $Criteria->compare('clntid', $id);
        $Criteria->group = 'pjctid';
        $count_deal = PaymentReport::model()->count($Criteria);


        $pages = new CPagination($count_deal);
        $pages->pageSize =5;
        $pages->applyLimit($Criteria);
        $listproject = PaymentReport::model()->findAll($Criteria);
        $this->render('view', array(
            'model' => $this->loadModel($id), 'getdata' => $listproject, 'pages' => $pages, 'clid' => $id
        ));
    }
    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate() {
        $model = new Clients;

        // Uncomment the following line if AJAX validation is needed
        $this->performAjaxValidation($model);


        if (isset($_POST['Clients'])) {
            $model->attributes = $_POST['Clients'];

            $model->created_by = yii::app()->user->id;
            $model->created_date = date('Y-m-d');

            $model->updated_by = yii::app()->user->id;
            $model->updated_date = date('Y-m-d');

            if ($model->save(false))
                if (!empty($_GET['asDialog'])) {
                    //Close the dialog, reset the iframe and update the grid
                    echo CHtml::script("window.parent.$('#cru-dialog').dialog('close');window.parent.$('#cru-frame').attr('src','');window.parent.$.fn.yiiGridView.update('{$_GET['gridId']}');");
                    Yii::app()->end();
                } else
                  Yii::app()->user->setFlash('success', 'Successfully updated.');
                    $this->redirect(array('clients/index'));
            //----- end new code --------------------
            // $this->redirect(array('Viewpartial','cid'=>$model->Clients));
            //$this->redirect(array('view','id'=>$model->cid));
        }
//----- begin new code --------------------
        if (!empty($_GET['asDialog']))
            $this->layout = '//layouts/iframe';
        //----- end new code --------------------
        $this->render('create', array(
            'model' => $model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    /* public function actionUpdate($id)
      {
      $model=$this->loadModel($id);

      // Uncomment the following line if AJAX validation is needed
      $this->performAjaxValidation($model);

      if(isset($_POST['Clients']))
      {
      $model->attributes=$_POST['Clients'];

      $model->updated_by = yii::app()->user->id;
      $model->updated_date = date('Y-m-d');

      if($model->save())
      $this->redirect(array('view','id'=>$model->cid));
      }

      $this->render('update',array(
      'model'=>$model,
      ));
      }
     */


    public function actionUpdate($id) {
        $model = $this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        $this->performAjaxValidation($model);

        if (isset($_POST['Clients'])) {
            $model->attributes = $_POST['Clients'];
            $model->updated_by = yii::app()->user->id;
            $model->updated_date = date('Y-m-d');

            if ($model->save())
            //----- begin new code --------------------
                if (!empty($_GET['asDialog'])) {
                    //Close the dialog, reset the iframe and update the grid
                    echo CHtml::script("window.parent.$('#cru-dialog').dialog('close');window.parent.$('#cru-frame').attr('src','');window.parent.$.fn.yiiGridView.update('{$_GET['gridId']}');");
                    Yii::app()->end();
                }else{
                //----- end new code --------------------
                  //  $this->redirect(array('viewpartial', 'cid' => $model->cid));
                     Yii::app()->user->setFlash('success', 'Successfully updated.');
                    $this->redirect(array('clients/index'));
             }
        }

        //----- begin new code --------------------
        if (!empty($_GET['asDialog']))
            $this->layout = '//layouts/iframe';
        //----- end new code --------------------

        $this->render('update', array(
            'model' => $model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id) {
        $this->loadModel($id)->delete();

        // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
        if (!isset($_GET['ajax']))
            $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $model = new Clients('search');
      //  print_r($model);die;
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Clients']))
            $model->attributes = $_GET['Clients'];

        $this->render('index', array(
            'model' => $model,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin() {
        $model = new Clients('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Clients']))
            $model->attributes = $_GET['Clients'];

        $this->render('admin', array(
            'model' => $model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.

protected/views/clients/_form.php
<?php
/* @var $this ClientsController */
/* @var $model Clients */
/* @var $form CActiveForm */
?>

<div class="form">

    <?php
    $form = $this->beginWidget('CActiveForm', array(
        'id' => 'clients-form',
        'enableAjaxValidation' => true,
        'clientOptions' => array(
            'validateOnSubmit' => true,
            'validateOnChange' => true,
            'validateOnType' => false,),
            ));
    ?>


    <?php //echo $form->errorSummary($model); ?>

    <div class="row">
        <div class="subrow">
            <?php echo $form->labelEx($model, 'name'); ?>
            <?php echo $form->textField($model, 'name', array('class'=>'form-control')); ?>
            <?php echo $form->error($model, 'name'); ?>
        </div>
   
    <div class="subrow">
        <?php echo $form->labelEx($model, 'nick_name'); ?>
        <?php echo $form->textField($model, 'nick_name', array('class'=>'form-control')); ?>
        <?php echo $form->error($model, 'nick_name'); ?>
    </div>
    </div>
    <div class="row">
        <div class="subrow">
        <?php echo $form->labelEx($model, 'project_type'); ?>
        <?php echo $form->dropDownList($model, 'project_type', CHtml::listData(ProjectType::model()->findAll(array('order' => 'project_type ASC')), 'ptid', 'project_type'), array('empty' => '--', 'class'=>'form-control')); ?>
        <?php echo $form->error($model, 'project_type'); ?>
    </div>

    <div class="subrow">
        <?php echo $form->labelEx($model, 'status'); ?>
        <div class="radio_btn">
            <?php
            echo $form->radioButtonList($model, 'status', CHtml::listData(Status::model()->findAll(
                            array(
                                'select' => array('sid,caption'),
                                'condition' => 'status_type="active_status"',
                                'order' => 'caption',
                                'distinct' => true
                    )),'sid','caption') , array(  'labelOptions'=>array('style'=>'display:inline'),'separator' => ''));
            ?>
        </div>
        <?php echo $form->error($model, 'status'); ?>
    </div>
    </div>
  
    <div class="row">
        <div class="subrow subrowlong">
         
        <?php echo $form->labelEx($model, 'description'); ?>
        <?php echo $form->textArea($model, 'description', array('rows' => 6,'class'=>'form-control')); ?>
        <?php echo $form->error($model, 'description'); ?>
    </div>        
    </div>
 

<div class="row buttons">
        <?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save',array('class'=>'btn blue')); ?>
        <?php echo CHtml::button('Cancel',array('class' => 'btn default','onclick'=>"window.parent.$('#cru-dialog').dialog('close');window.parent.$('#cru-frame').attr('src','');")); ?>
    </div>

    <?php $this->endWidget(); ?>

</div><!-- form -->
<style>
    #content{
        width: 500px; 
        /*border: 1px solid #ddd;*/
    }   
    div.form .row{ 
        width: 500px;
    }
    .subrow{
        width: 50%;
        float:left;
    }
    form .subrow {
        padding: 0 12px !important;
    }
    div.form input, div.form textarea, div.form select {
        margin: 0.2em 0 0.5em 0;
    }
    .subrowlong{
        /*        width: 500px;
                float:left;*/
    }
    .radio_btn label {
        display: inline-block !important;
        margin-right: 15px;
    }
    .blue.btn {
        margin-left: 30px;
    }
        


</style>

protected/views/clients/_search.php
<?php
/* @var $this ClientsController */
/* @var $model Clients */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'cid'); ?>
		<?php echo $form->textField($model,'cid'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'description'); ?>
		<?php echo $form->textArea($model,'description',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'status'); ?>
		<?php echo $form->textField($model,'status'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'created_date'); ?>
		<?php echo $form->textField($model,'created_date'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'created_by'); ?>
		<?php echo $form->textField($model,'created_by'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'updated_date'); ?>
		<?php echo $form->textField($model,'updated_date'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'updated_by'); ?>
		<?php echo $form->textField($model,'updated_by'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/clients/_view.php
<?php
/* @var $this ClientsController */
/* @var $data Clients */
?>

<div class="view">

    <b><?php echo CHtml::encode($data->getAttributeLabel('cid')); ?>:</b>
    <?php echo CHtml::link(CHtml::encode($data->cid), array('view', 'id' => $data->cid)); ?>
    <br />

    <b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
    <?php echo CHtml::encode($data->name); ?>
    <br />

    <b><?php echo CHtml::encode($data->getAttributeLabel('project_type')); ?>:</b>
    <?php echo CHtml::encode($data->project_type); ?>
    <br />

    <b><?php echo CHtml::encode($data->getAttributeLabel('description')); ?>:</b>
    <?php echo CHtml::encode($data->description); ?>
    <br />

    <b><?php echo CHtml::encode($data->getAttributeLabel('status')); ?>:</b>
    <?php echo CHtml::encode($data->status); ?>
    <br />

    <b><?php echo CHtml::encode($data->getAttributeLabel('created_date')); ?>:</b>
    <?php echo CHtml::encode($data->created_date); ?>
    <br />

    <b><?php echo CHtml::encode($data->getAttributeLabel('created_by')); ?>:</b>
    <?php echo CHtml::encode($data->created_by); ?>
    <br />

    <b><?php echo CHtml::encode($data->getAttributeLabel('updated_date')); ?>:</b>
    <?php echo CHtml::encode($data->updated_date); ?>
    <br />

    <?php /*
      <b><?php echo CHtml::encode($data->getAttributeLabel('updated_by')); ?>:</b>
      <?php echo CHtml::encode($data->updated_by); ?>
      <br />

     */ ?>

</div>

protected/views/clients/admin.php
<?php
/* @var $this ClientsController */
/* @var $model Clients */

$this->breadcrumbs = array(
    'Clients' => array('index'),
    'Manage',
);

$this->menu = array(
    array('label' => 'List Clients', 'url' => array('index')),
    array('label' => 'Create Clients', 'url' => array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('clients-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Clients</h1>

<?php echo CHtml::link('Advanced Search', '#', array('class' => 'search-button')); ?>
<div class="search-form" style="display:none">
    <?php
    $this->renderPartial('_search', array(
        'model' => $model,
    ));
    ?>
</div><!-- search-form -->

<?php
$createUrl = $this->createUrl('create', array("asDialog" => 1, "gridId" => 'address-grid'));
echo CHtml::link('Create Client', '#', array('onclick' => "$('#cru-frame').attr('src','$createUrl '); $('#cru-dialog').dialog('open');"));
?>

<?php
$this->widget('zii.widgets.grid.CGridView', array(
    'id' => 'clients-grid',
    'dataProvider' => $model->search(),
    'filter' => $model,
    'columns' => array(
        array('class' => 'IndexColumn', 'header' => 'Sl.No.',),
        array('name'=>'cid', 'htmlOptions' => array('width' => '40px','style'=>'font-weight: bold;text-align:center')),  
        'name',
		'nick_name',
        array(
            'name' => 'project_type',
            'value' => '$data->projectType->project_type',
            'type' => 'raw',
            'filter' => CHtml::listData(ProjectType::model()->findAll(
                            array(
                                'select' => array('ptid,project_type'),
                                'order' => 'project_type',
                                'distinct' => true
                    )), "ptid", "project_type")
        ),
        'description',
        array(
            'name' => 'status',
            'value' => '$data->status0->caption',
            'type' => 'raw',
            'filter' => CHtml::listData(Status::model()->findAll(
                            array(
                                'select' => array('sid,caption'),
                                'condition' => 'status_type="active_status"',
                                'order' => 'status_type',
                                'distinct' => true
                    )), "sid", "caption")
        ),
        'created_date',
        array(
            'class' => 'CButtonColumn',
            'template'=>'{view}{update}',
            'buttons' => array(
                /*'view' =>
                array(
                    'url' => 'Yii::app()->createUrl("clients/view", array("id"=>$data->cid,"asDialog"=>1))',
                    'options' => array(
                        'ajax' => array(
                            'type' => 'POST',
                            // ajax post will use 'url' specified above 
                            'url' => "js:$(this).attr('href')",
                            'update' => '#id_view',
                        ),
                    ),
                ),*/
             
                'update' =>
                array(
                    'url' => '$this->grid->controller->createUrl("update", array("id"=>$data->primaryKey,"asDialog"=>1,"gridId"=>$this->grid->id))',
                    'click' => 'function(){$("#cru-frame").attr("src",$(this).attr("href")); $("#cru-dialog").dialog("open");  return false;}',
                ),
            ),
        ),
    ),
));
?>
<?php
//--------------------- begin new code --------------------------
// add the (closed) dialog for the iframe
$this->beginWidget('zii.widgets.jui.CJuiDialog', array(
    'id' => 'cru-dialog',
    'options' => array(
        'title' => 'Detail view',
        'autoOpen' => false,
        'modal' => false,
        'width' => 620,
        'height' => 560,
    ),
));
?>
<iframe id="cru-frame" width="600" height="500" scrolling="auto"></iframe>
<?php
$this->endWidget();
//--------------------- end new code --------------------------
//the dialog
$this->beginWidget('zii.widgets.jui.CJuiDialog', array(
    'id' => 'dlg-clients-view',
    'options' => array(
        'title' => 'Detail view',
        'autoOpen' => false, //important!
        'modal' => true,
        'width' => 550,
        'height' => 470,
    ),
));
?>
<div id="id_view"></div>
<?php $this->endWidget(); ?>

protected/views/clients/create.php
<?php
/* @var $this ClientsController */
/* @var $model Clients */

$this->breadcrumbs=array(
	'Clients'=>array('index'),
	'Create',
);

?>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/clients/index.php
<?php
/* @var $this ClientsController */
/* @var $model Clients */

$this->breadcrumbs = array(
    'Clients',
);

if(yii::app()->user->role<=2){
	$this->menu = array(
//	    array('label' => 'Create Projects', 'url' => array('create')),
//	    array('label' => 'Manage Projects', 'url' => array('admin')),
	);
}

?>
<div class="clearfix">
    <div class="add link pull-right">
        <?php
        $createUrl = $this->createUrl('addclient', array("asDialog" => 1, "gridId" => 'address-grid'));
        echo CHtml::link('Add Client', '', array('class' => 'btn blue', 'onclick' => "$('#cru-frame').attr('src','$createUrl '); $('#cru-dialog').dialog('open');"));
        ?>
    </div>
    <h1>Clients</h1>
</div>

<?php 
$this->widget('zii.widgets.grid.CGridView', array(
    'id' => 'projects-grid',
    'dataProvider' => $model->search(),
    'ajaxUpdate'=>false,
    'itemsCssClass' => 'table table-bordered',
    'filter' => $model,
    'pager' => array( 'id'=>'dataTables-example_paginate',  'header' => '', 'prevPageLabel'=>'Previous ',
   'nextPageLabel'=>'Next ' ),
     
    'pagerCssClass'=>'dataTables_paginate paging_simple_numbers', 
    'columns' => array(
        array(
            'header' => 'S.No.',
            'value' => '$this->grid->dataProvider->pagination->currentPage * $this->grid->dataProvider->pagination->pageSize + ($row+1)',
        ),
       array('name'=>'cid', 'htmlOptions' => array('width' => '40px','style'=>'font-weight: bold;text-align:center')), 
       array(
        'name'  => 'name',
        'value' => 'CHtml::link($data->name, Yii::app()->createUrl("clients/view",array("id"=>$data->cid)))',
        'type'  => 'raw',
        'visible'=>(yii::app()->user->role==1),
        'filter'=> $this->widget('zii.widgets.jui.CJuiAutoComplete', array(
                'name'=>'Clients[name]',
                'source'=>$this->createUrl('Clients/autocomplete'),
                'value' => isset($model->name) ? $model->name: "",
                'options'=>array(
                    'focus'=>'js:function(event, ui) { 
                       $("#Clients_name").val(ui.item.value);
                    }',
                    'minLength'=>'1',
                    'showAnim'=>'fold',
                    'select'=>'js:function(event, ui) {  $("#Clients_name").val(ui.item.value); }'
               
                   ),
                 ),true),

    ),
          
        'nick_name',
	
        array(
            'name' => 'project_type',
            'value' => '$data->projectType->project_type',
            'type' => 'raw',
            'filter' => CHtml::listData(ProjectType::model()->findAll(
                            array(
                                'select' => array('ptid,project_type'),
                                'order' => 'project_type',
                                'distinct' => true
                    )), "ptid", "project_type")
        ),
        'description',
        array(
            'name' => 'status',
            'value' => '$data->status0->caption',
            'type' => 'raw',
            'filter' => CHtml::listData(Status::model()->findAll(
                            array(
                                'select' => array('sid,caption'),
                                'condition' => 'status_type="active_status"',
                                'order' => 'status_type',
                    )), "sid", "caption")
        ),
       

        array(
            'name'=>'created_date',
            //'value'=>'Yii::app()->dateFormatter->format("Y-m-d",strtotime($data->created_date))',
            'filter'=> $this->widget('zii.widgets.jui.CJuiDatePicker', array(
              'model'=>$model,
              'attribute'=>'created_date',
              'htmlOptions' => array(
              'id' => 'created_date'
              ),
              'options' => array(
              'showOn' => 'focus',
              'dateFormat' => 'yy-mm-dd',
               )
             ), true)
            
        ),
        /*
          'description',
          'created_date',
          'created_by',
          'updated_date',
          'updated_by',
         */
        array(
            'class' => 'CButtonColumn',
            'template' => '{view}{update}',
            'buttons'=>array(
                'view' => array(
                    'label'=>'',
                    'imageUrl' =>false,
                    'options' => array('class' => 'icon-eye icon-comn','title'=>'View'),
                   ),
                'update' => array(
                    'label'=>'',
                    'imageUrl' =>false,
                    'options' => array('class' => 'icon-pencil icon-comn','title'=>'Edit',),
                   ),
           ), 
        ),
    ),
));
?>

<?php
    $this->beginWidget('zii.widgets.jui.CJuiDialog', array(
    'id' => 'cru-dialog',
    'options' => array(
        'title' => 'Add Client',
        'autoOpen' => false,
        'modal' => false,
        'width' => 590,
        'height' => "auto",
    ),
));
?>
<iframe id="cru-frame" width="550" height="auto" frameborder="0"  style="min-height:325px;"></iframe>

<?php
$this->endWidget();
?>
<div id="id_view"></div>

<?php
    Yii::app()->clientScript->registerScript('myjavascript', '
    
    $( function() {

         (function($) {
            if (!$.curCSS) {
            $.curCSS = $.css;
        }
        })(jQuery);

        jQuery.fn.extend({
        propAttr: $.fn.prop || $.fn.attr
        });
   
   
  } );

');


?>

protected/views/clients/update.php
<?php
/* @var $this ClientsController */
/* @var $model Clients */

$this->breadcrumbs=array(
	'Clients'=>array('index'),
	$model->name=>array('view','id'=>$model->cid),
	'Update',
);

 
?>

<h2>Update Client: <span><?php echo $model->name; ?></span></h2>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>